project:
  type: website
  output-dir: docs

website:
  title: "Giulia Marchello"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
